### ISSUE TITLE
Question about scores_std

### ISSUE THREAD

**Issue by CSQianDong** [aliannejadi/qulac#3]
Hi, I'm confused aboud scores_std, how do you compute it? As I know, std=sqrt([(x1-x)^2 +...(xn-x)^2]/n). The final result is a number, but your scores_std is a vector. Really thank for your help.

**Comment by CSQianDong** [comment]
It will be appreciated if you could give me the code about how to compute scores_std or any other hints.

**Comment by aliannejadi** [comment]
Thanks for your message. 
The scores_std vector contains the std of ranking scores up to each position. For instance, scores_std[10] = std of ranking scores for top 10 documents; scores_std[120] = std of ranking scores for top 120 documents. At each position in the array, we use the same formula that you mentioned (std formula) to compute the scores.

**Comment by CSQianDong** [comment]
Thanks a lot~
