### ISSUE TITLE
Sorry to interrupt you again

### ISSUE THREAD

**Issue by CSQianDong** [aliannejadi/qulac#4]
I notice that documents you used in Qulac is already processed like this
"'magazine': 3.0,
  'articles': 1.0,
  'luxury': 14.0,
  'travel': 10.0,
  'news': 1.0,
  'columnist': 1.0
.................................".
Could I get the raw documents you used in Qulac? The whole Clueweb09 dataset is too large.
Thank you again.

**Comment by aliannejadi** [comment]
Thank you for your message. 
Let me check my files and get back to you.

**Comment by aliannejadi** [comment]
I tried to upload the files on the server but failed because of the size. Do you still need them? 
Please send me an email with your email address, so that I can find other services to pass them to you. My address: mohammad.alian.nejadi@usi.ch

**Comment by CSQianDong** [comment]
okok, appreciate~
