### ISSUE TITLE
Question about PointWise setting in NeuQS

### ISSUE THREAD

**Issue by CSQianDong** [aliannejadi/qulac#6]
Hi, as for as I know, poitwise is a strategy of LTR. It need a label such as a score or category. How do you get this label (score or category) , and could you release this data? Looking forward to your reply~

**Comment by aliannejadi** [comment]
Hi. Sorry for the late response.
We used the same labels that we used to train NeuQS. The data is already in the repository: eval_dict.json
Please note that a selected question is evaluated based on its effect on document retrieval performance. Therefore, a selected question and its corresponding answer are passed to the document retrieval component. The retrieval component re-ranks the documents. The evaluation result of the new ranked list would be the label of the question. So, the values in eval_dict (in terms of P@k, nDCG@k, MRR, etc) are actually the training/test labels.
Hope this helps.
Mohammad

**Comment by CSQianDong** [comment]
Really thank you for your patient help!
